exclude: |
    (?x)(
        /build/
    )

repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
     -  id: insert-license
        files: \.py|\.sh$
        args:
            - --license-filepath
            - .pre-commit-license-header.txt
            - --allow-past-years
            - --no-extra-eol
     -  id: insert-license
        files: \.java$
        args:
            - --license-filepath
            - .pre-commit-license-header.txt
            - --comment-style
            - //
            - --use-current-year
            - --allow-past-years
            - --no-extra-eol
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: trailing-whitespace
        exclude: '\.diff$'
        args: [--markdown-linebreak-ext=md]
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: end-of-file-fixer
        exclude: |
            (?x)(
                \.diff$
            )
    -   id: fix-byte-order-marker
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
    -   id: actionlint
# SC2028: Use printf instead of echo
# SC2129: Consider using { cmd1; cmd2; } >> file instead of individual redirects.
        args: ['-ignore', 'SC2028', '-ignore', 'SC2129']
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        exclude: '\.yml$'
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: ['--py39-plus', '--keep-runtime-typing']
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--filter-files"]
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
-   repo: local
    hooks:
        - id: mypy
          name: mypy
          files: qai_hub_models/.*(py|pyi|ipynb)$
          exclude: qai_hub_models/models/_internal/.*
          entry: scripts/util/run_mypy.sh
          language: system
